"""Move source to lead

Revision ID: 24aba9f324fc
Revises: 62637c105e63
Create Date: 2026-07-25 04:06:56.496837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24aba9f324fc'
down_revision: Union[str, Sequence[str], None] = '62637c105e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'source')
    op.add_column('leads', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'source')
    op.add_column('campaigns', sa.Column('source', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
